# Generated by Django 3.2.9 on 2023-04-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LivedoorNewscorpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('sentence', models.TextField()),
            ],
        ),
    ]
